Spring Intro Task
IvanLuchkin/spring-intro pull request #1
Opened 2021-02-08 11:42 UTC by IvanLuchkin

- AppConfig created
- Main class added for testing
- User created, UserDao and UserService implemented
- pom.xml updated
- .gitignore updated

2021-02-08 14:54 UTC, Mandybur800 approved these changes

2021-02-09 08:59 UTC, dmytro-hryhoruk requested changes
I don't see travis.yml file here

2021-02-09 08:59 UTC, dmytro-hryhoruk commented on .gitignore
> +target/
empty line

2021-02-09 08:59 UTC, dmytro-hryhoruk commented on src/main/java/spring/dao/UserDaoImpl.java
> +    private SessionFactory sessionFactory;
let's use constructor autowiring

2021-02-09 08:59 UTC, dmytro-hryhoruk commented on src/main/java/spring/service/UserServiceImpl.java
> +    private UserDao userDao;
same

2021-02-09 08:59 UTC, dmytro-hryhoruk commented on src/main/java/spring/dao/UserDaoImpl.java
> +    public void insert(User user) {
```suggestion
    public void add(User user) {
```

2021-02-09 09:41 UTC, dmytro-hryhoruk commented on src/main/java/spring/dao/UserDaoImpl.java
> +    public void insert(User user) {
either fix the comment or answer on it please)

2021-02-09 09:41 UTC, dmytro-hryhoruk approved these changes

2021-02-09 09:42 UTC, IvanLuchkin commented on src/main/java/spring/dao/UserDaoImpl.java
> +    public void insert(User user) {
Sorry, I've lost it. Fixed

2021-02-09 21:16 UTC, merged